
version: '3'

services:
  postgressrv:
    image: postgres
    container_name: postgresql
    hostname: postgresql
    environment:
      POSTGRES_PASSWORD: "Postgres!"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /home/erikson/Docker/Volumes/PostgreSQL:/var/lib/postgresql/data 