version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: myqql
    hostname: myqql
    environment:
      MYSQL_ROOT_PASSWORD: "MySql!"
    ports:
      - "3306:3306"
    volumes:
      - /home/erikson/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-compose-network